### ISSUE TITLE
Unrecognized field name "Raw".

### ISSUE THREAD

**Issue by matthieufaillot** [DeNardoLab/BehaviorDEPOT#6] opened 2022-07-12 16:52 UTC
Hi,
Congrats and thanks for making BehaviorDepot available. I am running BehaviorDepot v1.2 GUI on windows 10 with MATLAB 2022a (and dependency toolboxes) installed. When selecting a csv tracking file (from DLC), Matlab outputs the following error message. Do you have any idea what it could be related to ?
Matthieu
```
Select tracking file
Select video file
Loading video. May take some time depending on size of video.
Video Loaded
Reading tracking file
CSV Loaded
Tracking Structure Assembled
Hampel Correction Applied
Tracked 16 points
Unrecognized field name "Raw".

Error in smoothTracking_custom (line 20)
        time = (1:size(Tracking.Raw.(i_part), 2))';

Error in BehDEPOT_mainscript (line 113)
    Tracking = smoothTracking_custom(Tracking, Params);

Error in BehaviorDEPOT_GUI_v1_2/StartButtonPushed (line 386)
            BehDEPOT_mainscript(app.P)

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
```

**Comment by matthieufaillot** [comment] 2022-07-12 16:55
ps : when input is a h5 file it outputs a different error message :

`Error using readmatrix
'.h5' is not a recognized file extension. Unable to detect file type. To read the
file as a specific file type, regardless of file extension, use the 'FileType'
name-value pair.

Error in importDLCTracking (line 14)
            M = readmatrix(Params.tracking_file);

Error in BehDEPOT_mainscript (line 104)
    [data, Params] = importDLCTracking(Params);

Error in BehaviorDEPOT_GUI_v1_2/StartButtonPushed (line 386)
            BehDEPOT_mainscript(app.P)

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
`

**Comment by cjgabrie** [comment] 2022-07-12 18:12
Hi Matthieu,

Thanks for trying out BehaviorDEPOT!

For the CSV, it appears the file is being read but is not getting saved properly after import (and then crashes at the start of smoothing). I'm not 100% sure what's causing the problem just from the error message. 

For the H5, it seems like it's failing at import. We have switched over to using CSVs by default, so I think it's probably an issue with the Matlab function reading the tracking file, probably introduced in a Matlab update.

Would you mind uploading a sample of the CSV and H5 outputs that you are using from DLC? I'll look into the issues more closely and see if I can clean up these bugs for you.

Thanks,
Chris

**Comment by matthieufaillot** [comment] 2022-07-12 19:43
Hi Chris
Thanks for your message and your help
Here are the tracking files : 
h5 : https://drive.google.com/file/d/12sxiA-guuTS4ohb7dfEVqasECPJ9KokF/view?usp=sharing
csv : https://drive.google.com/file/d/1-jV6DfYEtbLm0Uvh44Ixi9K6GD5PY7V7/view?usp=sharing
Also I replicated the problem on MATLAB2020b ( I thought it could be a matlab version issue)
Best
Matthieu

**Comment by cjgabrie** [comment] 2022-07-13 16:55
Hi Matthieu,

Thanks for the sample files. Looking at the CSV, the problem is actually related to assignment of parts that aren't registered by BehaviorDEPOT (i.e. selecting 'Other', when registering parts). I am working on patching the code to fix this issue (and the H5 problem) and will reply here when I've got code uploaded for you.

Thanks,
Chris

**Comment by cjgabrie** [comment] 2022-07-13 19:29
The issue with the CSV files should be resolved (as long as you are tracking the minimum required points on the mouse, i.e. nose, ears, and tailbase). You can assign the various objects you are tracking to 'Other' during registration and they will be smoothed and come out in the Tracking structure with their original names.

You can try out the updated version using the install file on the main page of the repo.

I am still working on the H5 issue--this is related to the data being collected successfully, but the labels in the file not being retrieved. For now, you should be able to avoid this by using CSV files.

**Comment by cjgabrie** [comment] 2022-07-14 11:34
This should be fixed by my edits yesterday. The current version of calculateMetrics doesn't have that line, so it's clear you're using an older version. 

What's not immediately clear is if it's because the app packaging messed up or because of installation. Can you confirm that you re-installed using the .mlappinstall file from the main GitHub page? I will verify the file myself later and let you know if it needed changing.

**Comment by matthieufaillot** [comment] 2022-07-14 16:15
Hi Chris
Yes I installed using 1.3mlappinstall
Once I downloaded all the repo and clicked on the file, second time I only downloaded the file…
I ll try on another computer

**Comment by cjgabrie** [comment] 2022-07-25 14:43
Hi Matthieu,

Apologies for the delay on responding to this issue. I double checked your data with my most recent install, and it seems that the original CSV issue has been resolved. I'll keep this issue open until I can fix the H5 issue (which is just related to pulling the original data labels from the file).

The new issue you posted about appears to be a problem with the Exploration classifier, and I'd have to take a closer look to understand what's going on. Can you post a separate issue about this problem? Are you able to get through the pipeline using just a simple classifier (e.g. calculateMovement?). This will help me understand if its the data or something about the pipeline that is triggering the problem.

Lastly, I'm at a conference this week and probably won't be able to fix this until next week. I'll come back to this ASAP.

Thanks,
Chris

**Comment by matthieufaillot** [comment] 2022-07-27 21:31
Hi Chris, thanks a lot for your help
I was indeed able to a simpler classifier
I ll post a separate issue for the Exploration Classifier
Matthieu

**Comment by cjgabrie** [comment] 2022-10-11 09:12
Hi Matthieu,

Thanks for trying out BehaviorDEPOT!

For the CSV, it appears the file is being read but is not getting saved
properly after import (and then crashes at the start of smoothing). I'm not
100% sure what's causing the problem just from the error message.

For the H5, it seems like it's failing at import. We have switched over to
using CSVs by default, so I think it's probably an issue with the Matlab
function reading the tracking file, probably introduced in a Matlab update.

Would you mind uploading a sample of the CSV and H5 outputs that you are
using from DLC? I'll look into the issues more closely and see if I can
clean up these bugs for you.

Thanks,
Chris

**Comment by cjgabrie** [comment] 2022-12-27 17:38
Closing due to lack of activity

**Closed by cjgabrie** 2022-12-27 17:38 UTC
